services:
  - type: web
    name: lino-perfume
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn scentido.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "465"
      - key: EMAIL_USE_TLS
        value: "False"
      - key: EMAIL_USE_SSL
        value: "True"
      - key: EMAIL_HOST_USER
        value: mylino2026@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: irldxyvlyyhryxwl
      - key: DEFAULT_FROM_EMAIL
        value: LINO Atelier <mylino2026@gmail.com>
      - key: BREVO_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
