# Generated by Django 6.0.7 on 2026-08-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_changepasswordotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI / GPay / PhonePe'), ('card', 'Credit / Debit Card')], default='upi', max_length=20),
        ),
    ]
